apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-api
spec:
  template:
    spec:
      containers:
        - name: category-api
          env:
            - name: PGUSERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: pg.username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: pg.password
