bases:
  - ../base
  - ../base/postgres

namePrefix: spring-

configMapGenerator:
  - name: category-api-config
    files:
      - application.yml

secretGenerator:
  - name: postgres-secret
    literals:
      - pg.username=postgres
      - pg.password=postgres

images:
  - name: blueprint/category-api
    newName: blueprint/category-api-spring